# Generated by Django 4.0.5 on 2022-06-18 10:14

import django.core.validators
from django.db import migrations, models
import expenses_tracker.tracker_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[expenses_tracker.tracker_app.validators.only_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=15, validators=[expenses_tracker.tracker_app.validators.only_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('budget', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
