# Generated by Django 4.0.5 on 2022-06-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_expense_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='static/images/user.pmg', upload_to='images/', verbose_name='Profile Image'),
        ),
    ]
