# Generated by Django 4.0.5 on 2022-06-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0004_rename_profile_image_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='expenses_tracker/static/images/user.pmg', upload_to='images/', verbose_name='Profile Image'),
        ),
    ]
