# Generated by Django 4.0.5 on 2022-06-19 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='owner_profile',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='tracker_app.profile'),
            preserve_default=False,
        ),
    ]
